# Site settings
title: 阳光如初.
description: http://veryjava.cn/ 
favicon: /assets/img/avatar.JPG
baseurl: 
url: http://veryjava.cn/
rss_url:

# Build settings

#highlight: true
highlighter: pygments

timezone: Asia/Shanghai

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  auto_id_prefix: 'id-'